[package]
name = "wg-page-backend"
version = "0.1.0"
authors = ["HD <hannes-duerr@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
chrono = "^0"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
