[package]
name = "wg-page-backend"
version = "0.1.0"
authors = ["HD <hannes-duerr@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
