[package]
name = "wg-page-backend"
version = "0.1.0"
authors = ["HD <hannes-duerr@protonmail.com>"]
edition = "2021"
default-run = "wg-page-backend"

[[bin]]
name="diktator"
path="bin/diktator/main.rs"

[dependencies]
diesel = { version = "2", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
chrono = "^0"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
actix-web = "4.2.1"
derive_more = "0.99.17"
env_logger = "0.10.0"
